version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:
  doc_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: tr202/sogustika_backend
    env_file: .env
    volumes:
      - static_volume:/static/
      - media_volume:/app/media
      - type: bind
        source: ./data
        target: /app/data
        read_only: true
  frontend:
    image: tr202/sogustika_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  nginx:
    image: nginx:1.19.3
    stdin_open: true 
    tty: true        
    ports:
      - "80:80"
      - "443:443"
    restart: always  
    volumes:
      - static_volume:/usr/share/nginx/html/
      - media_volume:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

      