# Generated by Django 3.2 on 2023-08-02 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                default="Sogustika",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
