# Generated by Django 3.2 on 2023-07-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230710_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'ordering': ('recipe',), 'verbose_name': 'рецепт в избранном', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='favoriteuser',
            options={'verbose_name': 'любимого автора', 'verbose_name_plural': 'любимые авторы'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'рецепт', 'verbose_name_plural': 'рецепты'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('recipe',), 'verbose_name': 'корзину', 'verbose_name_plural': 'корзины'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
