# Generated by Django 3.2 on 2023-08-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_auto_20230804_1619"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recipe",
            name="Cookong time most be more than zero",
        ),
        migrations.RemoveConstraint(
            model_name="recipeingredient",
            name="Amount most be more than zero",
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                check=models.Q(cooking_time__gte=1),
                name="Cooking time most be more than zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.CheckConstraint(
                check=models.Q(amount__gte=1),
                name="Amount most be more than zero",
            ),
        ),
    ]
