# Generated by Django 3.2 on 2023-07-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230711_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipe_tag', through='recipes.TagRecipe', to='recipes.Tag'),
        ),
        migrations.DeleteModel(
            name='FavoriteUser',
        ),
    ]
