# Generated by Django 3.2 on 2023-07-11 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230710_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_subs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'любимого автора',
                'verbose_name_plural': 'любимые авторы',
            },
        ),
        migrations.AddConstraint(
            model_name='favoriteuser',
            constraint=models.UniqueConstraint(fields=('subscriber', 'user'), name='no_double_favorite'),
        ),
    ]
