# Generated by Django 3.2 on 2023-07-18 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230711_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteuser',
            options={'ordering': ('user',), 'verbose_name': 'любимого автора', 'verbose_name_plural': 'любимые авторы'},
        ),
    ]
