name: Main Sogustika workflow

on:
  push:
    branches:
      - main
      #- tests
      - develop

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/develop'
    steps:
    
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          sudo su 
          cd /var/lib/docker/
          rm -f overlay2/{,.}
          sudo reboot
